twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(APP_NAME)%'
    paths: 
        '%kernel.project_dir%/templates/themes/base_theme' : base_theme
when@test:
    twig:
        strict_variables: true
