twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(APP_NAME)%'
        theme: '@App\Theme\ThemeHelper'
    paths: 
        '%kernel.project_dir%/templates/themes/base_theme' : base_theme
    form_themes: ['@base_theme/form_theme.html.twig']
when@test:
    twig:
        strict_variables: true
