controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
presta_sitemap:
    resource: "@PrestaSitemapBundle/config/routing.yml"